twig:
#    default_path: '%kernel.project_dir%/templates'
#    form_themes:
#        - 'bootstrap_4_layout.html.twig'

    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'cnsv_bootstrap_4_layout.html.twig'
